### ISSUE TITLE
[Request]: Replace GridTracker2

### ISSUE THREAD

**Issue by d3m3vilurr** [KO6FCH/scoop-ham#1]
### Prerequisites

- [X] I have searched all issues/PRs to ensure it has not already been reported or fixed.

### Criteria

- [X] Criteria 1
- [X] Criteria 2
- [X] Criteria 3

### Name

GridTracker

### Description

GridTracker - An Amateur Radio Companion

### Homepage

https://gridtracker.org

### Download Link(s)

https://gridtracker.org/index.php/downloads/gridtracker-downloads

### Some Indication of Popularity/Repute

Recently, GridTracker was replaced to [version2][1] and a [site][2] / [package file name][3] was also changed.
that this reason package version is never updated.

[1]: https://gitlab.com/gridtracker.org/gridtracker2
[2]: https://gridtracker.org/index.php/downloads/gridtracker-downloads
[3]: https://download2.gridtracker.org/GridTracker2-2.241124.0-setup.exe

I try to manually change `gridtracker.json` just for installing

```
diff --git a/bucket/gridtracker.json b/bucket/gridtracker.json
index ac21653..433f4e0 100644
--- a/bucket/gridtracker.json
+++ b/bucket/gridtracker.json
@@ -1,14 +1,27 @@
 {
-    "version": "1.24.0922",
+    "version": "2.241124",
     "description": "GridTracker is a warehouse of amateur radio information presented in an easy to use interface, from live traffic decodes, logbooks, real-time spot reports, weather, current solar conditions and more!",
     "homepage": "https://gridtracker.org",
     "license": "BSD-3-Clause",
-    "url": "https://downloads.gridtracker.org/v1.24.0922/GridTracker-Installer.1.24.0922.exe#dl.7z",
-    "hash": "cb94308107524f4d8de923d9d4b716e2b8e93bcad08cd5cb6099c5054ecdde14",
+    "url": "https://download2.gridtracker.org/GridTracker2-2.241124.0-setup.exe#dl.7z",
+    "hash": "a5d36d177dcdbe916d146bc32ae71a7015c3b70bb22416626e27ccce43d9210a",
+    "extract_Dir": "$PLUGINSDIR",
+    "installer": {
+        "Script": [
+            "Remove-Item \"$dir\\*\" -Exclude 'app-64.7z'",
+            "Expand-7zipArchive \"$dir\\app-64.7z\" \"$dir\" -Removal"
+        ]
+    },
+    "bin": [
+        [
+            "GridTracker2.exe",
+            "GridTracker2"
+        ]
+    ],
     "shortcuts": [
         [
-            "GridTracker.exe",
-            "GridTracker"
+            "GridTracker2.exe",
+            "GridTracker2"
         ]
     ],
     "suggest":{
```

**Comment by KO6FCH** [comment]
Fixed, and thanks!
